### PR TITLE
Fix issues + javadoc + tests

### PR DESCRIPTION
**Pull request by senyast4745**
Add all needs JavaDocs, add close method to clent, add tests, update versions, add github actions support. Love OpenSource community)

### CODE REVIEW

**Comment by senyast4745** [comment]
fix #2

**Comment by kirbyquerby** [comment]
Thank you for your pull request! This is a lot of code -- could you please break it up into a series of smaller PRs? It would help greatly with code review and understanding each set of changes.

**Comment by senyast4745** [comment]
Hey.  I would like to break, but unfortunately I wrote everything in one
thread and I can’t simply and quickly split my code into a series of pull
requests.  Most of the changes are adding documentation and writing tests.

чт, 28 нояб. 2019 г., 4:46 kirbyquerby <notifications@github.com>:

**Comment by kirbyquerby** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

This should help you easily split the code up into multiple commits, which you can then separately PR. Unfortunately, your change contains lots of changes that aren't related to each other (there's over 1500 lines of changes) so it's not feasible to review them all together.

**Comment by senyast4745** [comment]
Thanks. I will try

чт, 28 нояб. 2019 г., 9:59 kirbyquerby <notifications@github.com>:

**Pull request closed without merging**
